name       : python-vcversioner
version    : 2.16.0.0
release    : 8
source     :
    - https://pypi.python.org/packages/c5/cc/33162c0a7b28a4d8c83da07bc2b12cee58c120b4a9e8bba31c41c8d35a16/vcversioner-2.16.0.0.tar.gz : dae60c17a479781f44a4010701833f1829140b1eeccd258762a74974aa06e19b
homepage   : https://github.com/habnabit/vcversioner
license    : ISC
component  : programming.python
summary    : Take version numbers from version control.
description: |
    Take version numbers from version control.
setup      : |
    %python3_setup
install    : |
    %python3_install
